import { randomBytes } from 'node:crypto';
import type { DbExecutor } from '@/db/executor';
import {
  CheckInUndoRefusedError,
  DoorPassCodeCollisionError,
  DoorPassNotAllowedError,
  DoorPassNotFoundError,
  DoorPassRevokedError,
  DoorScanIdTakenError,
  EventNotFoundError,
  TicketNotFoundError,
} from '@/server/lib/errors';
import {
  type DoorWindow,
  doorWindow,
  generatePassCode,
  normalisePassCode,
} from '@/server/lib/door-pass';
import {
  DOOR_UNDO_REASONS,
  DOOR_UNDO_WINDOW_MS,
  type DoorUndoReason,
} from '@/server/lib/door-rules';
import {
  type DoorVerdict,
  OFFLINE_LIST_VERSION,
  type OfflineList,
  clampOfflineTime,
  offlineDigest,
} from '@/server/lib/door-offline';
import { logger } from '@/server/lib/logger';
import { formatDhakaClock } from '@/lib/time';
import { parseScanToken, scanLogInput } from '@/server/lib/scan-token';
import type {
  DoorPassRecord,
  DoorRepository,
  DoorScanRecord,
  DoorTicket,
  NewDoorScan,
} from '@/server/repositories/door.repository';
import type { EventRecord, EventsRepository } from '@/server/repositories/events.repository';
import type { OrdersRepository } from '@/server/repositories/orders.repository';
import type { TicketsRepository } from '@/server/repositories/tickets.repository';

/**
 * ADR-030 — gate check-in. A gate pass (one event, one gate) lets a door
 * phone scan; nothing else. A scan is one short transaction around ONE
 * conditional UPDATE on the ticket (the inventory pattern, Invariant 2):
 * of any number of simultaneous scans of a ticket exactly one admits.
 * Every attempt is logged in door_scans; every check-in and undo writes
 * an order_events row (Invariant 6 in spirit). The phone's `scanId` makes
 * a retried request return the same answer — the person just admitted is
 * never turned away by their own retry.
 *
 * Inside a transaction only tx-bound statements run: a pool read there
 * could starve the pool while concurrent scans wait on the ticket row.
 */

export const PASS_CODE_ATTEMPTS = 3;
export const DOOR_SEARCH_LIMIT = 10;
export const DOOR_RECENT_SCANS = 10;

export type ScanMethod = 'qr' | 'typed' | 'search';

/** The log input of a search admit whose ticket id matched nothing. */
const UNKNOWN_TICKET_ID = '<unknown-ticket-id>';

export interface DoorContext {
  pass: DoorPassRecord;
  event: EventRecord;
  window: DoorWindow;
  /** Before doors open: scans are answered and logged, never checked in. */
  practice: boolean;
}

export interface ScanItem {
  /** Generated by the phone; the same id on a retry. */
  scanId: string;
  /** What the camera / scanner / keyboard produced (one of input, ticketId). */
  input?: string;
  /** A name-search admit. */
  ticketId?: string;
  /**
   * A name-search admit: the last 3 digits of the buying phone, as the
   * person at the gate said them. Checked here, never shown to the door.
   */
  phoneLast3?: string;
  method: ScanMethod;
  scannedAt?: Date;
  /**
   * ADR-034: a scan the phone answered OFFLINE and sends later. `verdict` is
   * what it showed the person; `supersedesScanId` the online request it
   * replaced when that request got no answer. Requires `scannedAt`.
   */
  offline?: { verdict: DoorVerdict; supersedesScanId?: string };
}

export type ScanResultKind =
  | 'admitted'
  | 'already_in'
  | 'cancelled'
  | 'wrong_event'
  | 'unknown'
  | 'practice_ok'
  | 'phone_mismatch'
  /** An offline door turned away a ticket the server would have admitted (logged only). */
  | 'turned_away'
  | 'scan_id_conflict'
  /** A replayed ADMIT that no longer stands (it was undone): scan again. */
  | 'rescan';

/** What the door screen shows. Never a ticket code, never buyer contact details. */
export interface ScanResult {
  scanId: string;
  result: ScanResultKind;
  practice: boolean;
  attendeeName?: string;
  ticketTypeName?: string;
  position?: number;
  total?: number;
  /** When it was checked in (admitted) or first checked in (already_in). */
  at?: Date;
  gate?: string;
  /** already_in: this same pass let them in. */
  byThisPass?: boolean;
  secondsAgo?: number;
  /** wrong_event: the event the ticket is for (titles are public). */
  otherEventTitle?: string;
  /**
   * The answer is a replay of an earlier request with this scan id. A
   * replayed ADMIT means "admitted N s ago": the door shows it green only
   * to the Retry button, amber to a fresh read (it could be a screenshot).
   */
  replayed?: boolean;
}

export interface DoorSearchResult {
  ticketId: string;
  attendeeName: string;
  ticketTypeName: string;
  status: 'issued' | 'cancelled';
  checkedInAt: Date | null;
  checkedInBy: string | null;
  /** False for a comp: no buying phone, so a search admit has no digits to check. */
  phoneOnFile: boolean;
}

export interface DoorRecentScan {
  scanId: string;
  result: string;
  method: string;
  at: Date;
  attendeeName: string | null;
  ticketTypeName: string | null;
  /** This pass's own admit, still standing, inside the undo window. */
  undoable: boolean;
}

export interface DoorStatus {
  issued: number;
  checkedIn: number;
  practice: boolean;
  recent: DoorRecentScan[];
  /** The server's clock: the door phone keeps its offline clock offset fresh with it. */
  serverTime: Date;
}

/** Admin: one double entry (ADR-034). */
export interface OfflineConflict {
  scanId: string;
  /** The gate whose offline phone admitted. */
  gate: string;
  /** What the server found: already in, or cancelled. */
  result: ScanResultKind;
  /** When the offline gate admitted (the phone's corrected clock). */
  admittedAt: Date;
  syncedAt: Date;
  ticketId: string | null;
  orderId: string | null;
  attendeeName: string | null;
  ticketTypeName: string | null;
  /** The check-in that beat it. */
  priorAt: Date | null;
  priorGate: string | null;
}

/** `paused`: the event was unpublished (draft) — its passes are refused until it is republished. */
export type PassState = 'practice' | 'active' | 'paused' | 'ended' | 'revoked';

export interface GatePassRow {
  pass: DoorPassRecord;
  state: PassState;
  scans: number;
  /** Scans made offline and synced later. */
  offlineScans: number;
  admitted: number;
  searchAdmits: number;
  lastScanAt: Date | null;
}

export interface DoorServiceDeps {
  door: DoorRepository;
  tickets: Pick<TicketsRepository, 'checkIn' | 'undoCheckIn'>;
  orders: Pick<OrdersRepository, 'insertEvent'>;
  events: Pick<EventsRepository, 'findById'>;
  runInTransaction: <T>(fn: (tx: DbExecutor) => Promise<T>) => Promise<T>;
  now?: () => Date;
  passCode?: () => string;
  /** The offline list's salt (ADR-034); fresh per download. */
  listSalt?: () => string;
}

/**
 * When a scan happened: an offline scan's corrected phone clock, else the
 * server's receipt. A synced offline admit is 'just now' only if it was.
 */
function scanTime(scan: DoorScanRecord): Date {
  return scan.mode === 'offline' && scan.scannedAt ? scan.scannedAt : scan.receivedAt;
}

function describe(
  ticket: DoorTicket,
): Pick<ScanResult, 'attendeeName' | 'ticketTypeName' | 'position' | 'total'> {
  return {
    attendeeName: ticket.attendeeName,
    ticketTypeName: ticket.ticketTypeName,
    position: ticket.position,
    total: ticket.orderQuantity,
  };
}

function passState(
  pass: DoorPassRecord,
  event: EventRecord,
  window: DoorWindow,
  at: Date,
): PassState {
  if (pass.revokedAt) return 'revoked';
  if (at.getTime() > window.validUntil.getTime()) return 'ended';
  // Mirrors authenticate(): a draft event refuses every pass.
  if (event.status === 'draft') return 'paused';
  if (at.getTime() < window.validFrom.getTime()) return 'practice';
  return 'active';
}

export function createDoorService({
  door,
  tickets,
  orders,
  events,
  runInTransaction,
  now = () => new Date(),
  passCode = generatePassCode,
  listSalt = () => randomBytes(16).toString('hex'),
}: DoorServiceDeps) {
  const secondsSince = (at: Date) =>
    Math.max(0, Math.floor((now().getTime() - at.getTime()) / 1000));

  /** The log row a replay must match: same pass, same thing scanned. */
  function sameScan(ctx: DoorContext, item: ScanItem, stored: DoorScanRecord): boolean {
    if (stored.passId !== ctx.pass.id) return false;
    if (item.ticketId) {
      return (
        stored.ticketId === item.ticketId ||
        (stored.ticketId === null && stored.input === UNKNOWN_TICKET_ID)
      );
    }
    const raw = item.input ?? '';
    return stored.input === scanLogInput(raw, parseScanToken(raw));
  }

  /** A scan id seen before: the same answer again, rebuilt from the log row. */
  async function replay(
    ctx: DoorContext,
    item: ScanItem,
    stored: DoorScanRecord,
  ): Promise<ScanResult> {
    const practice = stored.mode === 'practice';
    if (!sameScan(ctx, item, stored)) {
      return { scanId: item.scanId, result: 'scan_id_conflict', practice };
    }
    const base: ScanResult = { scanId: stored.scanId, result: stored.result, practice };
    if (!stored.ticketId) return base;
    const ticket = await door.findTicket({ id: stored.ticketId });
    if (!ticket) return base;
    if (stored.result === 'wrong_event') return { ...base, otherEventTitle: ticket.eventTitle };
    const described = { ...base, ...describe(ticket), replayed: true };
    if (stored.result === 'admitted') {
      // Replay green only while this very scan's check-in stands: once it
      // was undone, "ADMIT" would let someone in with nothing recorded.
      if (ticket.checkedInScanId !== stored.scanId) {
        return { scanId: stored.scanId, result: 'rescan', practice };
      }
      return {
        ...described,
        at: ticket.checkedInAt ?? stored.receivedAt,
        gate: ctx.pass.label,
        secondsAgo: secondsSince(ticket.checkedInAt ?? stored.receivedAt),
      };
    }
    if (stored.result === 'already_in' && stored.priorCheckedInAt) {
      return {
        ...described,
        at: stored.priorCheckedInAt,
        gate: stored.priorCheckedInBy ?? undefined,
        byThisPass:
          ticket.checkedInPassId === ctx.pass.id &&
          ticket.checkedInAt?.getTime() === stored.priorCheckedInAt.getTime(),
        secondsAgo: Math.max(
          0,
          Math.floor((stored.receivedAt.getTime() - stored.priorCheckedInAt.getTime()) / 1000),
        ),
      };
    }
    return described;
  }

  async function fresh(ctx: DoorContext, item: ScanItem): Promise<ScanResult> {
    const offline = item.offline;
    // An offline scan answered PRACTICE on the phone stays practice here too.
    const practice = ctx.practice || offline?.verdict === 'practice';
    const raw = item.input ?? '';
    let ticket: DoorTicket | null;
    let input: string;
    if (item.ticketId) {
      ticket = await door.findTicket({ id: item.ticketId });
      input = ticket?.code ?? UNKNOWN_TICKET_ID;
    } else {
      const code = parseScanToken(raw);
      input = scanLogInput(raw, code);
      ticket = code ? await door.findTicket({ code }) : null;
    }
    const log: Omit<NewDoorScan, 'result'> = {
      scanId: item.scanId,
      passId: ctx.pass.id,
      eventId: ctx.event.id,
      ticketId: ticket?.id ?? null,
      input,
      method: item.method,
      mode: offline ? 'offline' : practice ? 'practice' : 'online',
      scannedAt: item.scannedAt ?? null,
      doorVerdict: offline?.verdict ?? null,
      supersedesScanId: offline?.supersedesScanId ?? null,
    };

    if (!ticket) {
      await door.insertScan({ ...log, result: 'unknown' });
      return { scanId: item.scanId, result: 'unknown', practice };
    }
    if (ticket.eventId !== ctx.event.id) {
      // The other event's title is public; the attendee's name is not needed here.
      await door.insertScan({ ...log, result: 'wrong_event' });
      return {
        scanId: item.scanId,
        result: 'wrong_event',
        practice,
        otherEventTitle: ticket.eventTitle,
      };
    }

    // A name-search admit carries no QR, so the buying phone's last 3
    // digits stand in for it — checked here, so the door screen never has
    // to show them (an impostor could read them off it). A comp has none.
    if (
      item.method === 'search' &&
      ticket.buyerPhoneLast3 !== null &&
      item.phoneLast3 !== ticket.buyerPhoneLast3
    ) {
      await door.insertScan({ ...log, result: 'phone_mismatch' });
      return { scanId: item.scanId, result: 'phone_mismatch', practice, ...describe(ticket) };
    }

    // Nothing is checked in for a rehearsal, nor for an offline scan whose
    // door did not admit (it turned the person away, or undid its admit):
    // the answer it WOULD give is logged, and that is all. Only an offline
    // ADMIT is replayed as a check-in — the person is already inside.
    if (practice || (offline && offline.verdict !== 'admitted')) {
      const would =
        ticket.status === 'cancelled'
          ? 'cancelled'
          : ticket.checkedInAt
            ? 'already_in'
            : practice
              ? 'practice_ok'
              : 'turned_away';
      await door.insertScan({
        ...log,
        result: would,
        priorCheckedInAt: would === 'already_in' ? ticket.checkedInAt : null,
        priorCheckedInBy: would === 'already_in' ? ticket.checkedInBy : null,
      });
      return {
        scanId: item.scanId,
        result: would,
        practice,
        ...describe(ticket),
        ...(would === 'already_in' && ticket.checkedInAt
          ? { at: ticket.checkedInAt, gate: ticket.checkedInBy ?? undefined }
          : {}),
      };
    }

    const gate = ctx.pass.label;
    // An offline admit happened when the phone says (corrected, clamped),
    // not when signal came back. An online one: the database clock.
    const by = {
      gate,
      scanId: item.scanId,
      at:
        offline && item.scannedAt
          ? clampOfflineTime(item.scannedAt, ctx.window.validFrom, now())
          : undefined,
    };
    return runInTransaction(async (tx) => {
      // Pass first, ticket second (the same order as revoke-and-undo): a
      // revoke waits for this scan, or this scan sees the revoke.
      if (!(await door.lockActivePass(ctx.pass.id, tx))) {
        throw new DoorPassRevokedError(ctx.pass.id);
      }
      let admitted = await tickets.checkIn(ticket.id, by, tx);
      let current: DoorTicket | null = null;
      if (!admitted) {
        current = await door.findTicket({ id: ticket.id }, tx);
        // A concurrent undo landed between the failed UPDATE and this read:
        // the ticket is admissible again — try once more.
        if (current && current.status === 'issued' && !current.checkedInAt) {
          admitted = await tickets.checkIn(ticket.id, by, tx);
          // Lost again (another gate, or a cancel): `current` is stale — re-read below.
          if (!admitted) current = null;
        }
      }

      if (admitted) {
        await orders.insertEvent(
          {
            orderId: ticket.orderId,
            actor: `door:${gate}`,
            action: 'ticket.checked_in',
            fromStatus: null,
            toStatus: null,
            note: `${ticket.code} · ${gate} · ${item.method}${offline ? ' · offline' : ''}`,
          },
          tx,
        );
        await door.insertScan({ ...log, result: 'admitted' }, tx);
        return {
          scanId: item.scanId,
          result: 'admitted' as const,
          practice,
          ...describe(ticket),
          attendeeName: admitted.attendeeName,
          at: admitted.checkedInAt ?? undefined,
          gate,
        };
      }

      const latest = current ?? (await door.findTicket({ id: ticket.id }, tx));
      if (!latest || latest.status === 'cancelled') {
        await door.insertScan({ ...log, result: 'cancelled' }, tx);
        return { scanId: item.scanId, result: 'cancelled' as const, practice, ...describe(ticket) };
      }
      await door.insertScan(
        {
          ...log,
          result: 'already_in',
          priorCheckedInAt: latest.checkedInAt,
          priorCheckedInBy: latest.checkedInBy,
        },
        tx,
      );
      return {
        scanId: item.scanId,
        result: 'already_in' as const,
        practice,
        ...describe(latest),
        at: latest.checkedInAt ?? undefined,
        gate: latest.checkedInBy ?? undefined,
        byThisPass: latest.checkedInPassId === ctx.pass.id,
        secondsAgo: latest.checkedInAt ? secondsSince(latest.checkedInAt) : undefined,
      };
    });
  }

  /** One scan, idempotent by `scanId`. */
  async function scan(ctx: DoorContext, item: ScanItem): Promise<ScanResult> {
    const existing = await door.findScanByScanId(item.scanId);
    if (existing) return replay(ctx, item, existing);
    try {
      return await fresh(ctx, item);
    } catch (err: unknown) {
      // The same scan raced its own retry; the loser rolled back — answer
      // exactly what the winner recorded.
      if (err instanceof DoorScanIdTakenError) {
        const stored = await door.findScanByScanId(item.scanId);
        if (stored) return replay(ctx, item, stored);
      }
      throw err;
    }
  }

  return {
    /**
     * @throws EventNotFoundError, DoorPassNotAllowedError
     */
    async createPass(eventId: string, label: string, actor: string): Promise<DoorPassRecord> {
      const event = await events.findById(eventId);
      if (!event) throw new EventNotFoundError(eventId);
      if (event.status !== 'published') throw new DoorPassNotAllowedError('not_published');
      if (doorWindow(event).validUntil.getTime() <= now().getTime()) {
        throw new DoorPassNotAllowedError('window_ended');
      }
      for (let attempt = 1; ; attempt++) {
        try {
          const pass = await door.insertPass({
            eventId,
            label,
            code: passCode(),
            createdBy: actor,
          });
          logger.info({ actor, eventId, passId: pass.id, label }, 'gate pass created');
          return pass;
        } catch (err: unknown) {
          if (err instanceof DoorPassCodeCollisionError && attempt < PASS_CODE_ATTEMPTS) continue;
          throw err;
        }
      }
    },

    /**
     * `eventId` is the event the page showed: a pass of another event is
     * "not found", so a stale page can never revoke the wrong gate.
     * @throws DoorPassNotFoundError
     */
    async revokePass(eventId: string, passId: string, actor: string): Promise<void> {
      const pass = await door.findPassById(passId);
      if (!pass || pass.eventId !== eventId) throw new DoorPassNotFoundError(passId);
      await door.revokePass(passId);
      logger.info({ actor, passId }, 'gate pass revoked');
    },

    /**
     * Recovery from a leaked pass: revoke it and undo every check-in it made
     * that still stands, each with its own audit row. Returns how many.
     * @throws DoorPassNotFoundError
     */
    async revokeAndUndo(
      eventId: string,
      passId: string,
      reason: string,
      actor: string,
    ): Promise<number> {
      const pass = await door.findPassById(passId);
      if (!pass || pass.eventId !== eventId) throw new DoorPassNotFoundError(passId);
      const undone = await runInTransaction(async (tx) => {
        await door.revokePass(passId, tx);
        const standing = await door.ticketsCheckedInByPass(passId, tx);
        let n = 0;
        for (const t of standing) {
          // Compare-and-swap on this pass's scan: a ticket undone and
          // re-admitted at another gate since the read keeps that check-in.
          const row = await tickets.undoCheckIn(t.id, tx, t.checkedInScanId);
          if (!row) continue;
          await orders.insertEvent(
            {
              orderId: t.orderId,
              actor,
              action: 'ticket.check_in_undone',
              fromStatus: null,
              toStatus: null,
              note: `${t.code} · pass ${pass.label} revoked: ${reason}`,
            },
            tx,
          );
          n++;
        }
        return n;
      });
      logger.info({ actor, passId, undone }, 'gate pass revoked and its check-ins undone');
      return undone;
    },

    /**
     * The door phone's credential check, on every request. Null when the
     * code is wrong, the pass revoked, its window over, or the event pulled
     * back to draft. An ARCHIVED event keeps scanning until the window ends
     * — archiving promises issued tickets stay valid.
     */
    async authenticate(rawCode: string): Promise<DoorContext | null> {
      const code = normalisePassCode(rawCode);
      if (!code) return null;
      const pass = await door.findPassByCode(code);
      if (!pass || pass.revokedAt) return null;
      const event = await events.findById(pass.eventId);
      if (!event || event.status === 'draft') return null;
      const window = doorWindow(event);
      const at = now().getTime();
      if (at > window.validUntil.getTime()) return null;
      return { pass, event, window, practice: at < window.validFrom.getTime() };
    },

    scan,

    /** One after another — never in parallel (each is its own short transaction). */
    async scanBatch(ctx: DoorContext, items: ScanItem[]): Promise<ScanResult[]> {
      const out: ScanResult[] = [];
      const seen = new Map<string, ScanResult>();
      for (const item of items) {
        const r = seen.get(item.scanId) ?? (await scan(ctx, item));
        seen.set(item.scanId, r);
        out.push(r);
      }
      return out;
    },

    /**
     * The door undoes its OWN admit, within 2 minutes (a mis-tap, the wrong
     * person) — long enough to fix a slip, too short to recycle a ticket.
     * @throws CheckInUndoRefusedError
     */
    async undoOwnAdmit(ctx: DoorContext, scanId: string, reason: DoorUndoReason): Promise<void> {
      const scan = await door.findScanByScanId(scanId);
      if (!scan || scan.result !== 'admitted' || !scan.ticketId) {
        throw new CheckInUndoRefusedError('not_found');
      }
      if (scan.passId !== ctx.pass.id) throw new CheckInUndoRefusedError('not_yours');
      if (now().getTime() - scanTime(scan).getTime() > DOOR_UNDO_WINDOW_MS) {
        throw new CheckInUndoRefusedError('too_late');
      }
      const ticketId = scan.ticketId;
      await runInTransaction(async (tx) => {
        if (!(await door.lockActivePass(ctx.pass.id, tx))) {
          throw new DoorPassRevokedError(ctx.pass.id);
        }
        const undone = await tickets.undoCheckIn(ticketId, tx, scanId);
        if (!undone) throw new CheckInUndoRefusedError('not_checked_in');
        await orders.insertEvent(
          {
            orderId: undone.orderId,
            actor: `door:${ctx.pass.label}`,
            action: 'ticket.check_in_undone',
            fromStatus: null,
            toStatus: null,
            note: `${undone.code} · ${DOOR_UNDO_REASONS[reason]}`,
          },
          tx,
        );
      });
    },

    /**
     * The organizer undoes a check-in (B8), with a reason. A compare-and-swap
     * on what the page showed — the order and the check-in's scan id — so a
     * stale page can never clear a later check-in; the audit note says which
     * check-in (time · gate) was taken back.
     * @throws CheckInUndoRefusedError, TicketNotFoundError
     */
    async undoCheckInAsAdmin(
      ticketId: string,
      {
        orderId,
        expectedScanId,
        reason,
        actor,
      }: { orderId: string; expectedScanId: string; reason: string; actor: string },
    ): Promise<{ code: string }> {
      return runInTransaction(async (tx) => {
        const before = await door.findTicket({ id: ticketId }, tx);
        if (!before || before.orderId !== orderId) throw new TicketNotFoundError(ticketId);
        const undone = await tickets.undoCheckIn(ticketId, tx, expectedScanId);
        if (!undone) throw new CheckInUndoRefusedError('not_checked_in');
        // The CAS matched, so `before` describes exactly the check-in undone.
        const was = before.checkedInAt
          ? ` (in ${formatDhakaClock(before.checkedInAt)} · ${before.checkedInBy ?? '?'})`
          : '';
        await orders.insertEvent(
          {
            orderId: undone.orderId,
            actor,
            action: 'ticket.check_in_undone',
            fromStatus: null,
            toStatus: null,
            note: `${undone.code}${was}: ${reason}`,
          },
          tx,
        );
        return { code: undone.code };
      });
    },

    /** Name substring (2+ characters) or a ticket code, within the pass's event. */
    async search(ctx: DoorContext, rawTerm: string): Promise<DoorSearchResult[]> {
      const term = rawTerm.trim().replace(/\s+/g, ' ');
      if (term.length < 2) return [];
      return door.searchTickets(
        ctx.event.id,
        { name: term, code: parseScanToken(term) },
        DOOR_SEARCH_LIMIT,
      );
    },

    async status(ctx: DoorContext): Promise<DoorStatus> {
      const [counts, recent] = await Promise.all([
        door.counts(ctx.event.id),
        door.recentScans(ctx.pass.id, DOOR_RECENT_SCANS),
      ]);
      const serverTime = now();
      const at = serverTime.getTime();
      return {
        ...counts,
        practice: ctx.practice,
        serverTime,
        recent: recent.map((r) => ({
          scanId: r.scan.scanId,
          result: r.scan.result,
          method: r.scan.method,
          at: scanTime(r.scan),
          attendeeName: r.attendeeName,
          ticketTypeName: r.ticketTypeName,
          undoable:
            r.scan.result === 'admitted' &&
            r.stillCheckedInByThisScan &&
            at - scanTime(r.scan).getTime() <= DOOR_UNDO_WINDOW_MS,
        })),
      };
    },

    /**
     * ADR-034: every ticket of the pass's event, for the phone to answer
     * from when there is no signal. Codes go out only as salted hashes, and
     * nothing about the buyer goes at all — no phone digits either, which is
     * why a name-search admit needs signal.
     */
    async offlineList(ctx: DoorContext): Promise<OfflineList> {
      const rows = await door.offlineList(ctx.event.id);
      const salt = listSalt();
      const entries = await Promise.all(
        rows.map(async (r) => ({
          d: await offlineDigest(salt, r.code),
          id: r.id,
          name: r.attendeeName,
          type: r.ticketTypeName,
          pos: r.position,
          of: r.orderQuantity,
          status: r.status,
          inAt: r.checkedInAt?.toISOString() ?? null,
          inBy: r.checkedInBy,
        })),
      );
      return {
        v: OFFLINE_LIST_VERSION,
        eventId: ctx.event.id,
        passId: ctx.pass.id,
        salt,
        serverTime: now().toISOString(),
        validFrom: ctx.window.validFrom.toISOString(),
        validUntil: ctx.window.validUntil.toISOString(),
        entries,
      };
    },

    /** Admin: the event's double entries — offline admits the server could not honour. */
    async offlineConflicts(eventId: string): Promise<OfflineConflict[]> {
      const rows = await door.offlineConflicts(eventId);
      return rows.map((r) => ({
        scanId: r.scanId,
        gate: r.gate,
        result: r.result,
        admittedAt: r.scannedAt ?? r.receivedAt,
        syncedAt: r.receivedAt,
        ticketId: r.ticketId,
        orderId: r.orderId,
        attendeeName: r.attendeeName,
        ticketTypeName: r.ticketTypeName,
        priorAt: r.priorCheckedInAt,
        priorGate: r.priorCheckedInBy,
      }));
    },

    /** Admin: the event's passes with their state and how much they did. */
    async listPasses(event: EventRecord): Promise<GatePassRow[]> {
      const window = doorWindow(event);
      const at = now();
      const rows = await door.listPasses(event.id);
      return rows.map((r) => ({ ...r, state: passState(r.pass, event, window, at) }));
    },
  };
}

export type DoorService = ReturnType<typeof createDoorService>;
